### ISSUE TITLE
Database Documentations and Sampling

### ISSUE THREAD

**Issue by coopie** [group-24/Palpitate#11]
<Cale will fill this in with information>

**Comment by kren1** [comment]
Can we put the features extracted from the data into a relational database. I think that would solve a lot of our problems.

Firstly, Weka has a good integration with some SQL databses so it would be really easy to import the features there.

Secondly it would also vastly reduce the amount of data we are dealing with. I don't want to be running around with 150GB of data. It's 2015 after all.

Also I think giving some structure to the data is always a good idea.

**Comment by kren1** [comment]
I had a think about how to best structure the database. IMO the best solution is to have:

data(~~subjectID, featureID, batchID~~,featureValue)  - stores all the data
features(~~featureID~~, feature description, ...) - feature description for our reference mostly
batches(~~batchID~~, batch description,...) -  the batch when these feature was added, so we can have multiple version of feature extraction in the same database

(strikethrough is primary key, because of how great markdown is)

data(batchID) ==> bacthes(batchID)
data(featureID) ==> features(featureID)

The other alternatives I see are having one table with ~5000 columns for each feature, which is unmanagable imo (it might be easier to integrate with wekka though). Alternatevly we can have that rotated 90 degrees so we have ~70 columns for each subject, which is also unmanageable and I think is not a natural data structure. We could also have a table for each feature which I don't think is wise either.

If there are no major objections to it, I'll work on it tommorow.

**Comment by tlfrd** [comment]
The proposed structure is good. What SQL database should we use?
I'm sure you have already seen the list here. I don't have much experience
with any of them. MySQL looks like it could be quite easy to set up with JDBC.
http://weka.wikispaces.com/How+do+I+connect+to+a+database%3F

**Comment by kren1** [comment]
I was kind of hoping we can use csg provided postgres. I don't think there is a difference between easiness of  setup with respect to weka between them.

**Comment by kren1** [comment]
I think #13 fully address all this issue intended to do. Closing
